### ISSUE TITLE
New Component: Box

### ISSUE THREAD

**Issue by alkamin** [raster-foundry/blasterjs#87]

**Comment by designmatty** [comment]
**Package this component should live in:**
Core

**Context**
The Box is a catch-all, barebones component which provides access to all styled-system props. It's a component which can be modified and extended as needed and will be the backbone of many components in Blaster.

**Examples**
This component has no default styling.

**Implementation details:**
- Reference the Box component from the [.pulse framework](https://github.com/heartbeatua/Pulse-Boilerplate/blob/master/src/components/atoms/Box/Box.js)
- For your styled-system import statement @alkamin recommends the following:
  - `import styledSystem from "styled-system"`
  - and then later on, use `${styledSystem.space}` instead of having to type everything twice
- Let's not include styled-system `buttonStyle` as Box will not be used for our Button component
- Ultimately, use best judgement for adding/removing styled-system props as seen fit.
